language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2
jdk:
  - openjdk8
  - oraclejdk8
notifications:
  irc:
    channels:
      - "irc.esper.net#anidev"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
