language: java
# We want to cache the Maven directories so that we can speed up future
# builds by not redownloading all dependencies.
cache:
  directories:
  - .autoconf
  - $HOME/.m2
# Because Sponge is only compatible with Java 8 (due to the use of Optionals),
# we can only test build against Java 8. The source will remain at 7 for the other
# modules, so they will compile and run fine.
jdk:
  - oraclejdk8
notifications:
  irc:
    channels:
      - "irc.esper.net#anidev"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
