language: java
# We want to cache the Maven directories so that we can speed up future
# builds by not redownloading all dependencies.
cache:
  directories:
  - .autoconf
  - $HOME/.m2
# Because this server is hosted by Travis and it's extremely efficient,
# we can test this against openjdk7, oraclejdk7, and oraclejdk8 without
# wasting build time.
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
notifications:
  irc:
    channels:
      - "irc.esper.net#anidev"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
